version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    links:
      - db
    volumes:
      - .:/usr/src/app
  db:
    image: mariadb
    restart: always
    volumes:
      - ./database/database.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: admin
      MYSQL_PASSWORD: Jala123?
      MYSQL_DATABASE: jala
    ports:
      - "8889:3306"    
  
